framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
            'App\Message\RegisterEmail': async
            'App\Message\ProjectUserAddEmail': async
            'App\Message\MentionedByEmail': async
